# FUNCTIONAL PROGRAMMING

In [17]:
items = [1,2,3,4,5]
for i in items:
    print(i)

1
2
3
4
5


#### MAP | LAMBDA

In [23]:
def inc(x): return x
list(map(inc,items))

[1, 2, 3, 4, 5]

In [24]:
list(map((lambda x: x),items))

[1, 2, 3, 4, 5]

#### FILTER | REDUCE

In [25]:
list(filter((lambda x: x < 4), items))

[1, 2, 3]

In [26]:
from functools import reduce
reduce((lambda x,y: x/y), items)

0.008333333333333333

#### LIST COMPREHENSION

In [36]:
import numpy as np
item = np.arange(0, 10)
for i in item:
    if i > 3:
        print(i*i)

16
25
36
49
64
81


In [31]:
S = [x**2 for x in range(10) if x > 3]
S

[16, 25, 36, 49, 64, 81]

# NUMPY

In [4]:
import numpy as np
print('list')
c = np.array([[1, 2, 3],[4, 5, 6]])
print(c)
print('tuples')
d = np.array(((1, 2, 3),(4, 5, 6)))
print(d)
print('tuples and interconnected lists')
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
print(e)

list
[[1 2 3]
 [4 5 6]]
tuples
[[1 2 3]
 [4 5 6]]
tuples and interconnected lists
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### ARANGE | RESHAPE | LINSPACE | RANDOM()
ARANGE() create one-dimensional arrays; together with RESHAPE() it can generate two-dimensional arrays.
LINSPACE() is similar with ARANGE(), its first two arguments the initial and end values of the sequence, the third defines the number of elements into which we want the interval to be split
RANDOM() creates arrays already containing random values

In [7]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
# One dimensional
np.random.random(3)

array([0.16449236, 0.37383134, 0.04939961])

In [10]:
np.random.random((3,3))

array([[0.51414649, 0.27783832, 0.93951868],
       [0.32380351, 0.84529791, 0.63537816],
       [0.98851953, 0.27706552, 0.27173404]])

## BASIC OPERATIONS
In NumPy, these operations are element-wise, that is, the operators are applied only between corresponding elements

In [15]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [13]:
a+4

array([4, 5, 6, 7])

In [16]:
a*2

array([0, 2, 4, 6])

In [17]:
a

array([0, 1, 2, 3])

In [19]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [20]:
a+b

array([ 4,  6,  8, 10])

In [21]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [22]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

#### MULTIDIMENSIONAL

In [24]:
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
B = np.ones((3, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
A + B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## AGGREGATE FUNCTIONS
sum() | min() | max() | mean() | std() 

## INDEXING
Array indexing uses square brackets ([ ]) to index the elements of the array so that the elements can then be referred individually when extracting a value, selecting items, or even assigning a new value. Index is also automatically created

In [37]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [38]:
a[4]

14

In [42]:
a[-1]

15

In [44]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [45]:
A[1, 2]

15

## SLICING
Slicing allows you to extract portions of an array. In Python lists, the resulting arrays are copied. In NumPy, the
arrays are views of the same underlying buffer. Use colons (:) within square brackets. 
Index of first element : (X-1) is number of element : Intervals (default=1)

In [46]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [48]:
a[1:3]

array([11, 12])

In [49]:
a[1::2]

array([11, 13, 15])

In [54]:
a[::2]

array([10, 12, 14])

In [56]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

##### ROW

In [65]:
A[0,:]

array([10, 11, 12])

##### COLUMN

In [58]:
A[:,0]

array([10, 13, 16])

## ITERATING

##### FOR CONSTRUCT

In [3]:
import numpy as np
a = np.arange(10, 16)
for i in a:
    print(i)

10
11
12
13
14
15


In [5]:
import numpy as np
a = np.arange(10, 19).reshape((3, 3))
for i in a:
    print(i)

[10 11 12]
[13 14 15]
[16 17 18]


##### USE OF FLAT 

In [7]:
import numpy as np
a = np.arange(10, 19).reshape((3, 3))
for i in a.flat:
    print(i)

10
11
12
13
14
15
16
17
18


##### APPLY_LONG_AXIS FUNCTION
The most optimal way to iterate while making an aggregate function that returns a value calculated for every single column or on every single row (axis equals 0, then the iteration evaluates the elements column by column, whereas if axis equals 1 then the iteration evaluates the elements row by row.

In [12]:
import numpy as np
a = np.arange(10, 19).reshape((3, 3))
print(a)
print ('-- long axis --')
np.apply_along_axis(np.mean, axis=0, arr=a)

[[10 11 12]
 [13 14 15]
 [16 17 18]]
-- long axis --


array([13., 14., 15.])

In [14]:
np.apply_along_axis(np.max, axis=1, arr=a)

array([12, 15, 18])

#### CONDITIONS AND BOOLEAN ARRAYS

In [3]:
import numpy as np
A = np.random.random((4, 4))
A

array([[0.49757168, 0.16980655, 0.26573471, 0.81317705],
       [0.56240177, 0.16913435, 0.10594623, 0.66685466],
       [0.29351629, 0.59974904, 0.52991503, 0.69468408],
       [0.28696111, 0.94463375, 0.87334124, 0.77554824]])

In [4]:
A < 0.5

array([[ True,  True,  True, False],
       [False,  True,  True, False],
       [ True, False, False, False],
       [ True, False, False, False]])

In [8]:
A[A < 0.5]

array([0.49757168, 0.16980655, 0.26573471, 0.16913435, 0.10594623,
       0.29351629, 0.28696111])

#### SHAPE MANIPULATION (RESHAPE | SHAPE | RAVEL)

The reshape() function returns a new array and can therefore create new objects.

In [10]:
a = np.random.random(12)
a

array([0.21457443, 0.84871571, 0.23486289, 0.08421336, 0.82253086,
       0.19065002, 0.07983993, 0.99667068, 0.97242861, 0.88545521,
       0.74625446, 0.81918301])

In [12]:
A = a.reshape(3, 4)
A

array([[0.21457443, 0.84871571, 0.23486289, 0.08421336],
       [0.82253086, 0.19065002, 0.07983993, 0.99667068],
       [0.97242861, 0.88545521, 0.74625446, 0.81918301]])

However if you want to modify the object by modifying the shape, you have to assign a tuple containing the new dimensions directly to its shape attribute.

In [13]:
a.shape = (3, 4)
a

array([[0.21457443, 0.84871571, 0.23486289, 0.08421336],
       [0.82253086, 0.19065002, 0.07983993, 0.99667068],
       [0.97242861, 0.88545521, 0.74625446, 0.81918301]])

The inverse operation is also possible, that is, you can convert a two-dimensional array into a one-dimensional array, by using the ravel() function.

In [15]:
a.ravel()

array([0.21457443, 0.84871571, 0.23486289, 0.08421336, 0.82253086,
       0.19065002, 0.07983993, 0.99667068, 0.97242861, 0.88545521,
       0.74625446, 0.81918301])

#### TRANSPOSE
Transpose inverts column with rows

In [24]:
import numpy as np
A = np.random.random((3, 4))
A

array([[0.28840276, 0.87432129, 0.26472383, 0.97275258],
       [0.82102534, 0.41138443, 0.85819967, 0.83576115],
       [0.43829684, 0.98945501, 0.50372114, 0.99137756]])

In [21]:
A.transpose()

array([[0.552561  , 0.95205824, 0.2803204 ],
       [0.00901255, 0.98307601, 0.50190618],
       [0.79341143, 0.07427383, 0.50729776],
       [0.53106877, 0.98628305, 0.96812671]])

### ARRAY MANIPULATION

In [26]:
A = np.ones((3, 3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
B = np.zeros((3, 3))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### VSTACK | HSTACK

In [31]:
np.vstack((A, B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.hstack((A, B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

#### ROW_STACK | COLUMN_STACK
Generally these functions are used with one-dimensional arrays,

In [33]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [34]:
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [35]:
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### SPLITTING ARRAYS (HSPLIT | VSPLIT | SPLIT)

In [37]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
[B,C] = np.hsplit(A, 2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [41]:
[B,C] = np.vsplit(A, 2)

In [42]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
#row (axis = 0) : column (axis =1)  
[A1,A2,A3] = np.split(A,[1,2],axis=1)
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [59]:
A2

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [60]:
A3

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### COPIES OR VIEWS OF OBJECTS

In [64]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [63]:
b = a
b

array([1, 2, 3, 4])

In [68]:
a[2] = 0
a

array([1, 2, 0, 4])

In [69]:
b

array([1, 2, 3, 4])

In [76]:
c = a.copy()
c

array([1, 2, 0, 4])

In [79]:
a[1] = 0
a

array([1, 0, 0, 4])

In [80]:
c

array([1, 2, 0, 4])

# Reading and Writing Array Data on Files

In [81]:
data=([[ 0.86466285, 0.76943895, 0.22678279],
[ 0.12452825, 0.54751384, 0.06499123],
[ 0.06216566, 0.85045125, 0.92093862],
[ 0.58401239, 0.93455057, 0.28972379]])

In [82]:
np.save('saved_data',data)

In [83]:
loaded_data = np.load('saved_data.npy')

In [84]:
loaded_data

array([[0.86466285, 0.76943895, 0.22678279],
       [0.12452825, 0.54751384, 0.06499123],
       [0.06216566, 0.85045125, 0.92093862],
       [0.58401239, 0.93455057, 0.28972379]])

# Reading Files with Tabular Data | genfromtxt()

In [85]:
data = np.genfromtxt('ch3_data.csv', delimiter=',', names=True)

In [86]:
data

array([(1., 123., 1.4, 23.), (2., 110., 0.5, 18.), (3., 164., 2.1, 19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')])

In [87]:
data['id']

array([1., 2., 3.])